type: resource
name: Handler
namespace:
  name: acorn
properties:
  action:
    type: enum
    enumValues:
      - CREATE
      - UPDATE
      - DELETE
      - GET
      - LIST
    defaultValue:
      CREATE
  $type:
    type: string
  order:
    type: enum
    enumValues:
      - BEFORE
      - AFTER
    defaultValue:
      BEFORE
  do:
    type: object
---
type: nano/Code
name: acorn/handlers/Handler.js
language: JAVASCRIPT
content:
  $file: './Handler.js'